### ISSUE TITLE
Plagiarism - Act of Crime

### ISSUE THREAD

**Issue by mahine-learning-OP** [ayushmankumar7/Fast-Segementation#1]
Your interest in this Computer Vision domain of Machine Learning is appreciated, but your implementation highly reminds of a certain work of a GitHub user kshitizrimal. Your code is eerily similar to that of his, even the variable and method name. I believe plagiarism in the research-oriented work is very much not appreciated. I would recommend you to cite the true owner of this code in your ReadMe.md file of your Github Repository. 
Being in this industry for the last 10 years, I would like to suggest that you better think twice before performing such an act. And on further inspecting your GitHub profile, I found that you are a DSC Lead. I'm pretty sure that you are also aware of the fact that stealing code is an act of crime and is not tolerated among the Developer Community and that too of Google.

https://medium.com/deep-learning-journals/fast-scnn-explained-and-implemented-using-tensorflow-2-0-6bd17c17a49e

**Comment by ayushmankumar7** [comment]
@mahine-learning-OP  Thank you for your comment. Sure. I will mention the owner of the code in the readme. Once again thank you for letting me know.
